import type { Circle, NetworkState, Person } from "./types";

const d = (iso: string) => new Date(iso).getTime();

const YOU_ID = "you";

const people: Person[] = [
  {
    id: YOU_ID,
    name: "Du",
    city: "München",
    lat: 48.14,
    lng: 11.58,
    region: "süd",
    values: ["Freiheit", "Verantwortung", "Bodenständigkeit"],
    note: "Der Ursprung dieses Netzes. Von hier aus wachsen die Kreise.",
    addedAt: d("2023-03-12"),
    isYou: true,
  },
  {
    id: "lena",
    name: "Lena Hartwig",
    city: "München",
    lat: 48.14,
    lng: 11.58,
    region: "süd",
    values: ["Handwerk", "Familie", "Stille"],
    note: "Tischlerin in Haidhausen. Kennt dich seit der Schulzeit.",
    addedAt: d("2023-04-02"),
  },
  {
    id: "jonas",
    name: "Jonas Keller",
    city: "Augsburg",
    lat: 48.37,
    lng: 10.9,
    region: "süd",
    values: ["Freiheit", "Natur", "Mut"],
    note: "Wanderführer. Offenes Haus, kennt halb Schwaben.",
    addedAt: d("2023-04-02"),
  },
  {
    id: "mira",
    name: "Mira Sen",
    city: "München",
    lat: 48.14,
    lng: 11.58,
    region: "süd",
    values: ["Bildung", "Verantwortung", "Stille"],
    note: "Lehrerin. Klare Haltung, ruhiger Tisch.",
    addedAt: d("2023-04-18"),
  },
  {
    id: "ruth",
    name: "Ruth Eicher",
    city: "Passau",
    lat: 48.57,
    lng: 13.43,
    region: "süd",
    values: ["Familie", "Natur", "Bodenständigkeit"],
    note: "Hof an der Donau. Gästezimmer über dem Stall.",
    addedAt: d("2023-09-08"),
  },
  {
    id: "tobias",
    name: "Tobias Brunn",
    city: "Stuttgart",
    lat: 48.78,
    lng: 9.18,
    region: "süd",
    values: ["Handwerk", "Unabhängigkeit", "Bodenständigkeit"],
    note: "Schreinerei. Ladt zum Wochenende ein, ohne Umstände.",
    addedAt: d("2024-01-14"),
  },
  {
    id: "clara",
    name: "Clara Weißenbach",
    city: "Freiburg",
    lat: 47.99,
    lng: 7.85,
    region: "süd",
    values: ["Natur", "Freiheit", "Stille"],
    note: "Im Schwarzwald. Wer zu Fuß kommt, bleibt länger.",
    addedAt: d("2024-01-14"),
  },
  {
    id: "nils",
    name: "Nils Auer",
    city: "Nürnberg",
    lat: 49.45,
    lng: 11.08,
    region: "süd",
    values: ["Bildung", "Mut", "Verantwortung"],
    note: "Historiker. Verbindet den Süden mit dem Main.",
    addedAt: d("2024-02-03"),
  },
  {
    id: "hanna",
    name: "Hanna Vogel",
    city: "Frankfurt",
    lat: 50.11,
    lng: 8.68,
    region: "mitte",
    values: ["Unabhängigkeit", "Bildung", "Freiheit"],
    note: "Verlegerin. Große Wohnung am Main, immer ein Bett.",
    addedAt: d("2024-06-21"),
  },
  {
    id: "benno",
    name: "Benno Graf",
    city: "Würzburg",
    lat: 49.79,
    lng: 9.95,
    region: "süd",
    values: ["Bildung", "Freiheit", "Mut"],
    note: "Winzer. Der Keller ist der Treffpunkt.",
    addedAt: d("2024-06-21"),
  },
  {
    id: "elias",
    name: "Elias Kranz",
    city: "Köln",
    lat: 50.94,
    lng: 6.96,
    region: "west",
    values: ["Familie", "Handwerk", "Bodenständigkeit"],
    note: "Bäckerei in Ehrenfeld. Morgens um fünf ist schon jemand da.",
    addedAt: d("2024-11-09"),
  },
  {
    id: "farah",
    name: "Farah Demir",
    city: "Düsseldorf",
    lat: 51.23,
    lng: 6.78,
    region: "west",
    values: ["Bildung", "Mut", "Verantwortung"],
    note: "Juristin. Hilft unkompliziert, fragt nicht lange.",
    addedAt: d("2024-11-09"),
  },
  {
    id: "otto",
    name: "Otto Lind",
    city: "Hamburg",
    lat: 53.55,
    lng: 9.99,
    region: "nord",
    values: ["Natur", "Freiheit", "Stille"],
    note: "Kapitän a. D. Gästezimmer in Altona mit Blick aufs Wasser.",
    addedAt: d("2025-04-16"),
  },
  {
    id: "lina",
    name: "Lina Berg",
    city: "Hannover",
    lat: 52.37,
    lng: 9.73,
    region: "mitte",
    values: ["Familie", "Verantwortung", "Freiheit"],
    note: "Hebamme. Verbindet Westen und Norden, kennt jedes Haus.",
    addedAt: d("2025-04-16"),
  },
  {
    id: "samuel",
    name: "Samuel Ortiz",
    city: "Bremen",
    lat: 53.08,
    lng: 8.8,
    region: "nord",
    values: ["Handwerk", "Unabhängigkeit", "Natur"],
    note: "Bootsbauer. Werkstatt am Wasser, Kaffee ist immer warm.",
    addedAt: d("2025-05-02"),
  },
  {
    id: "svea",
    name: "Svea Holm",
    city: "Kiel",
    lat: 54.32,
    lng: 10.14,
    region: "nord",
    values: ["Natur", "Unabhängigkeit", "Mut"],
    note: "Segelt. Der Hafen ist offen, wenn der Wind passt.",
    addedAt: d("2025-08-19"),
  },
  {
    id: "paul",
    name: "Paul Rabe",
    city: "Berlin",
    lat: 52.52,
    lng: 13.4,
    region: "ost",
    values: ["Bildung", "Freiheit", "Stille"],
    note: "Buchhändler in Prenzlauer Berg. Keller voller Reserve.",
    addedAt: d("2025-12-04"),
  },
  {
    id: "ida",
    name: "Ida Köhler",
    city: "Leipzig",
    lat: 51.34,
    lng: 12.37,
    region: "ost",
    values: ["Handwerk", "Familie", "Bodenständigkeit"],
    note: "Töpferei. Kennt halb Sachsen, lädt ohne Ankündigung ein.",
    addedAt: d("2025-12-04"),
  },
  {
    id: "moritz",
    name: "Moritz Stein",
    city: "Dresden",
    lat: 51.05,
    lng: 13.74,
    region: "ost",
    values: ["Bildung", "Natur", "Verantwortung"],
    note: "Restaurator. Ruhiger Gastgeber an der Elbe.",
    addedAt: d("2026-03-11"),
  },
];

const circles: Circle[] = [
  {
    id: "isar",
    name: "Isar-Runde",
    hue: "sage",
    memberIds: ["you", "lena", "jonas", "mira"],
    formedAt: d("2023-04-18"),
    note: "Der Kern. Monatlicher Abend in Haidhausen.",
  },
  {
    id: "donau",
    name: "Donau-Blick",
    hue: "clay",
    memberIds: ["you", "mira", "ruth"],
    formedAt: d("2023-09-08"),
    note: "Wochenenden in Passau. Kein Programm, nur Ankommen.",
  },
  {
    id: "schwaben",
    name: "Schwaben-Tisch",
    hue: "umber",
    memberIds: ["jonas", "tobias", "clara", "nils"],
    formedAt: d("2024-02-03"),
    note: "Werkstatt-Treffen, vierteljährlich. Holz, Karte, Gespräch.",
  },
  {
    id: "mainlinie",
    name: "Mainlinie",
    hue: "slate",
    memberIds: ["nils", "hanna", "benno"],
    formedAt: d("2024-06-21"),
    note: "Wein und Gespräch. Würzburg oder Frankfurt.",
  },
  {
    id: "rhein",
    name: "Rhein-Abend",
    hue: "dusk",
    memberIds: ["hanna", "elias", "farah"],
    formedAt: d("2024-11-09"),
    note: "Drei Städte, ein Tisch. Meist Köln, manchmal Frankfurt.",
  },
  {
    id: "werkstatt",
    name: "Werkstatt",
    hue: "stone",
    memberIds: ["lena", "tobias", "elias", "ida"],
    formedAt: d("2025-01-20"),
    note: "Leute, die mit den Händen denken. Kein Ort, ein Halt.",
  },
  {
    id: "kueste",
    name: "Küstenband",
    hue: "pine",
    memberIds: ["elias", "otto", "lina", "samuel"],
    formedAt: d("2025-05-02"),
    note: "Wer nach Norden will. Hannover ist die Schwelle.",
  },
  {
    id: "nordlicht",
    name: "Nordlicht",
    hue: "moss",
    memberIds: ["otto", "svea", "samuel"],
    formedAt: d("2025-08-19"),
    note: "Wasserleute. Kiel, Hamburg, Bremen.",
  },
  {
    id: "elbe",
    name: "Elbe-Kreis",
    hue: "slate",
    memberIds: ["otto", "paul", "ida"],
    formedAt: d("2025-12-04"),
    note: "Zwischen Hamburg und Berlin, über Leipzig.",
  },
  {
    id: "ostwind",
    name: "Ostwind",
    hue: "clay",
    memberIds: ["paul", "ida", "moritz"],
    formedAt: d("2026-03-11"),
    note: "Sachsen und Berlin. Ruhig, fest, ohne Lärm.",
  },
];

export const SEED_NETWORK: NetworkState = { people: withContact(people), circles };

function withContact(list: Person[]): Person[] {
  const mail = (id: string) => `${id}@zirkel.example`;
  const byId: Record<string, Pick<Person, "profession" | "email" | "phone">> = {
    you: { profession: "", email: "", phone: "" },
    lena: { profession: "Handwerk", email: mail("lena"), phone: "+49 170 000 1102" },
    jonas: { profession: "Beratung", email: mail("jonas"), phone: "" },
    mira: { profession: "Lehre", email: mail("mira"), phone: "" },
    ruth: { profession: "Landwirtschaft", email: mail("ruth"), phone: "+49 170 000 1105" },
    tobias: { profession: "Handwerk", email: mail("tobias"), phone: "" },
    clara: { profession: "Landwirtschaft", email: mail("clara"), phone: "" },
    nils: { profession: "Lehre", email: mail("nils"), phone: "" },
    hanna: { profession: "Verlag", email: mail("hanna"), phone: "" },
    benno: { profession: "Landwirtschaft", email: mail("benno"), phone: "" },
    elias: { profession: "Gastronomie", email: mail("elias"), phone: "" },
    farah: { profession: "Anwalt", email: mail("farah"), phone: "+49 170 000 1112" },
    otto: { profession: "Seefahrt", email: mail("otto"), phone: "+49 170 000 1113" },
    lina: { profession: "Hebamme", email: mail("lina"), phone: "+49 170 000 1114" },
    samuel: { profession: "Handwerk", email: mail("samuel"), phone: "" },
    svea: { profession: "Seefahrt", email: mail("svea"), phone: "" },
    paul: { profession: "Handel", email: mail("paul"), phone: "" },
    ida: { profession: "Handwerk", email: mail("ida"), phone: "" },
    moritz: { profession: "Handwerk", email: mail("moritz"), phone: "" },
  };
  return list.map((p) => ({
    ...p,
    profession: byId[p.id]?.profession ?? "",
    email: byId[p.id]?.email ?? "",
    phone: byId[p.id]?.phone ?? "",
  }));
}

export function emptyNetwork(): NetworkState {
  const you = SEED_NETWORK.people.find((p) => p.isYou)!;
  return {
    people: [
      {
        ...you,
        addedAt: Date.now(),
        note: "Du. Bilde deinen ersten Kreis — drei Menschen genügen.",
      },
    ],
    circles: [],
  };
}

export const YOU_PERSON_ID = YOU_ID;
